app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

product:
    type:     rest
    resource: AppBundle\Controller\ProductController

categorie:
    type:     rest
    resource: AppBundle\Controller\CategorieController
